server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wxdemo
    username: root
    password: efuture
  mvc:
    view:
      suffix: .html
      prefix: /

openai:
  baseUrl: http://ec2-52-15-239-174.us-east-2.compute.amazonaws.com:9877
  apiKey: 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


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
